### PR TITLE
add genznodes info

### PR DESCRIPTION
**Pull request by PolkaVio**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Hey @PolkaVio, please use `PolkaVio` as your directory name. By the way, it seems this is not the account you used in register?

**Comment by PolkaVio** [comment]
@taramakage hmm i forgot i filled form with my team moniker name or use personal , any suggest ?

**Comment by taramakage** [comment]
> @taramakage hmm i forgot i filled form with my team moniker name or use personal , any suggest ?

Is `genzenode` your team moniker? And you've registered with `Genz22` which seems to be your team github account?

**Comment by taramakage** [comment]
> @taramakage hmm i forgot i filled form with my team moniker name or use personal , any suggest ?

Is `genzenode` your team moniker? And you've registered with `Genz22` which seems to be your team github account?

**Comment by PolkaVio** [comment]
nah , well I remember was filled form with @genz22 and @genznodes-ecosystem forgot to put @PolkaVio 
Genz22 is members in genznodes : https://github.com/Genz22

**Comment by taramakage** [comment]
> nah , well I remember was filled form with @Genz22 and @genznodes-ecosystem forgot to put @PolkaVio Genz22 is members in genznodes : https://github.com/Genz22

Got it. You can still fill the form with your info if you want to take the game independently. If you and your team member want to join the game as a whole, I think one GitHub account is enough. It's your choice.

**Comment by taramakage** [comment]
> can we keep the name genznodes and you replace your github account with @PolkaVio or @genznodes-ecosystem ?

No problem! I'll keep @PolkaVio.

**Comment by PolkaVio** [comment]
nice! do I need to fork it on my github, or stay in https://github.com/genznodes-ecosystem/gon-evidence/tree/main ?

**Comment by taramakage** [comment]
> nice! do I need to fork it on my github, or stay in https://github.com/genznodes-ecosystem/gon-evidence/tree/main ?

Depending on how convenient it is for you! I would suggest staying in `genznodes-ecosystem`, then I close this PR and merge the latter one.

**Comment by PolkaVio** [comment]
do I need create pr again ? @taramakage

**Pull request closed without merging**
