### PR TITLE
Nodeist evidence

### PR DESCRIPTION
**Pull request by nodeiistt**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Hey @nodeiistt, it seems that you didn't put your evidence file in the directory named after your GitHub username `nodeiistt`. Please make a modification.

**Comment by nodeiistt** [comment]
> Hey @nodeiistt, it seems that you didn't put your evidence file in the directory named after your GitHub username `nodeiistt`. Please make a modification.

done

**Review by taramakage — APPROVED** [review]

**Comment by nodeiistt** [comment]
Normally, the nodeist account belongs to us :)
https://github.com/Nodeist

But PR does not open, because it is corporate account.

Still no problem :)

**Comment by taramakage** [comment]
> Normally, the nodeist account belongs to us :) https://github.com/Nodeist
> 
> But PR does not open, because it is corporate account.
> 
> Still no problem :)

One personal account is sufficient for submitting evidence in GoN! Anyways, thank you for the reminder.

**Pull request merged**
