### PR TITLE
add RockX evidence

### PR DESCRIPTION
**Pull request by AlexRockX**
add RockX evidence

### CODE REVIEW

**Comment by taramakage** [comment]
Hey @AlexRockX, we notice the registration time of the GitHub account is less than one year. :cry:

**Comment by AlexRockX** [comment]
@taramakage  Because I just joined rockx for less than a year, need some additional proof from me, or from my experienced colleague? very willing to verify identity

**Comment by taramakage** [comment]
> @taramakage Because I just joined rockx for less than a year, need some additional proof from me, or from my experienced colleague? very willing to verify identity

Oh, it's not necessary to prove that! It's just that we have set a one-year threshold in our rules, and it wouldn't be good to violate this rule. I suggest using an account that has been active for over a year to resubmit. Please understand that we have set this threshold to filter out spam accounts, and it is not intended to target professional developers!

**Comment by AlexRockX** [comment]
@taramakage  recreate the PR at #70

**Pull request closed without merging**
