### PR TITLE
Add Wetez

### PR DESCRIPTION
**Pull request by wetezos**

### CODE REVIEW

**Comment by wetezos** [comment]
Wetez

**Comment by taramakage** [comment]
Hey @wetezos, we can't find you in our registration form. Have you registered before?

**Comment by wetezos** [comment]
> Hey @wetezos, we can't find you in our registration form. Have you registered before?

Hi @taramakage , The github we filled in when registering is wetezos and the corresponding team is Wetez, can you check the registration information again?

**Comment by taramakage** [comment]
> > Hey @wetezos, we can't find you in our registration form. Have you registered before?
> 
> Hi @taramakage , The github we filled in when registering is wetezos and the corresponding team is Wetez, can you check the registration information again?

Checked again, still not found. Can you fill the form again?

**Comment by wetezos** [comment]
> > > Hey @wetezos, we can't find you in our registration form. Have you registered before?
> > 
> > 
> > Hi @taramakage , The github we filled in when registering is wetezos and the corresponding team is Wetez, can you check the registration information again?
> 
> Checked again, still not found. Can you fill the form again?

OK, I've just resubmitted the form. Could you please check again, thank you very much

**Comment by taramakage** [comment]
Confirmed!

**Review by taramakage — APPROVED** [review]

**Pull request merged**
