### PR TITLE
dankuzone_w_daic evidence

### PR DESCRIPTION
**Pull request by DAICers**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Please change the name of your directory to DAICers. We require this because we use GitHub usernames in verifying evidence. Thanks for your understanding!

**Comment by DAICers** [comment]
We'll create a new one

**Comment by DAICers** [comment]
New PR:
https://github.com/game-of-nfts/gon-evidence/pull/105

**Comment by taramakage** [comment]
> New PR: #105

Done.

**Pull request closed without merging**
