### PR TITLE
UniqLabs A1-A6 tasks + A7-A20 tasks

### PR DESCRIPTION
**Pull request by uniqlabsorg**

### CODE REVIEW

**Review by taramakage — APPROVED** [review]

**Comment by taramakage** [comment]
Check details then find your uptick addr in info sheet dosen't match that in transfer hash
- in register:  `uptick1yve7w0gp5jfwmxe85nwguxs53hffd099h0cg64`
- in transfer: `uptick1xgcp08fw4j5ugtg96ld73w7cqcyrckx0hqv60z`

**Comment by uniqlabsorg** [comment]
Sorry but I couldn't remember at what point I registered the address ending in "cg64". Yes, it is my other address, but not even 1 tx has been made with this address on the uptick_7000-2 chain. This is the address I use for all my GoN missions: uptick1xgcp08fw4j5ugtg96ld73w7cqcyrckx0hqv60z

I also used this uptick address in the following tasks and I see that I got points from them: A8, A9, A11, A12

**Comment by taramakage** [comment]
> Sorry but I couldn't remember at what point I registered the address ending in "cg64". Yes, it is my other address, but not even 1 tx has been made with this address on the uptick_7000-2 chain. This is the address I use for all my GoN missions: uptick1xgcp08fw4j5ugtg96ld73w7cqcyrckx0hqv60z
> 
> I also used this uptick address in the following tasks and I see that I got points from them: A8, A9, A11, A12

You may have noticed that in A8 (and of course A9, A11, A12) we have a `never-go-back` style flow. This means that we can calculate your `ibc/hash` finally on the Iris chain, and in that case, we don't need to validate your Uptick, Stars, or Juno address (because we don't even collect your TxHashes).

However, for the "revisit" and "backtrace" style, we need to validate each IBC transaction because the NFT may experience class trace elimination. And only with each Txhash, we know that you made that transfer.

```
i --(1)--> s --(1)--> u --(1)--> s --(1)--> j --(1)--> i

i --(1)--> s --(1)--> j --(1)--> i
```

Note the above two flows, which have the same `ibc/hash` on the Iris chain, but the first one needs two more transactions, right? That's where the revisit happened. This is why in these tasks, we collect every transaction. We need to know that you have indeed made that transfer, and the recipient address is used here for validation.

I would suggest you update your uptick addr in the info sheet to regain these points! I will merge you PR next Monday and update the score card.

**Comment by uniqlabsorg** [comment]
> > Sorry but I couldn't remember at what point I registered the address ending in "cg64". Yes, it is my other address, but not even 1 tx has been made with this address on the uptick_7000-2 chain. This is the address I use for all my GoN missions: uptick1xgcp08fw4j5ugtg96ld73w7cqcyrckx0hqv60z
> > I also used this uptick address in the following tasks and I see that I got points from them: A8, A9, A11, A12
> 
> You may have noticed that in A8 (and of course A9, A11, A12) we have a `never-go-back` style flow. This means that we can calculate your `ibc/hash` finally on the Iris chain, and in that case, we don't need to validate your Uptick, Stars, or Juno address (because we don't even collect your TxHashes).
> 
> However, for the "revisit" and "backtrace" style, we need to validate each IBC transaction because the NFT may experience class trace elimination. And only with each Txhash, we know that you made that transfer.
> 
> ```
> i --(1)--> s --(1)--> u --(1)--> s --(1)--> j --(1)--> i
> 
> i --(1)--> s --(1)--> j --(1)--> i
> ```
> 
> Note the above two flows, which have the same `ibc/hash` on the Iris chain, but the first one needs two more transactions, right? That's where the revisit happened. This is why in these tasks, we collect every transaction. We need to know that you have indeed made that transfer, and the recipient address is used here for validation.
> 
> I would suggest you update your uptick addr in the info sheet to regain these points! I will merge you PR next Monday and update the score card.

Now better understood and thank you for warning. This is the last pr i created and i updated the uptick address on this pr.

https://github.com/game-of-nfts/gon-evidence/pull/597

**Pull request merged**
