### PR TITLE
Stage 3 evidence for B1-B2 + Update Uptick address + B5,B6,B7 tasks

### PR DESCRIPTION
**Pull request by uniqlabsorg**
I also request A13, A14, A15, A18, A19, A20 tasks that are not scored in Stage-2 be rechecked. I am sure that I have completed these tasks correctly.

### CODE REVIEW

**Comment by uniqlabsorg** [comment]
> I also request A13, A14, A15, A18, A19, A20 tasks that are not scored in Stage-2 be rechecked. I am sure that I have completed these tasks correctly.

The registered Uppick address has been updated to fix the errors.

**Review by taramakage — APPROVED** [review]

**Comment by uniqlabsorg** [comment]
According to the final scoreboard, it seems that I can't scored from A5, A15, A16, A17, A19 tasks. May I know the reason for this? Moreover, I had already scored points from A5, A16 and A17 tasks and I did not change them.

**Comment by uniqlabsorg** [comment]
I also think I should get points for the b7 task. Could you please review again.

**Comment by taramakage** [comment]
> I also think I should get points for the b7 task. Could you please review again.

B7:Race: race flow unexpected.

**Pull request merged**
