### PR TITLE
Add GoldenCom evidence

### PR DESCRIPTION
**Pull request by superdreams**
Add GoldenCom evidence

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Please change the name of your directory from `GoldenCom` to `superdreams`. We require this because we use GitHub usernames in verifying evidence. Thanks for your understanding!

**Comment by taramakage** [comment]
By the way, we can't find you on Discord by your discord handle. Can you confirm this?

**Comment by superdreams** [comment]
1f16c71a7cc003c750bb50cffb6b302

**Comment by superdreams** [comment]
> 

The file directory name has been changed to superdreams, thank you！

**Review by taramakage — APPROVED** [review]

**Pull request merged**
