### PR TITLE
Fixed template error

### PR DESCRIPTION
**Pull request by omercanyenigun**

### CODE REVIEW

**Review by taramakage — APPROVED** [review]

**Comment by omercanyenigun** [comment]
@taramakage hi, I'm on the score table as UnknownTeam:@omercanyenigun. I did all the tasks with state-3. (I uploaded state-3 today) It should show as team name:omercanyenigun and have my score. Can you review again?

**Comment by omercanyenigun** [comment]
@taramakage when is the deadline?

**Comment by taramakage** [comment]
> @taramakage when is the deadline?

The deadline for the full game is March 27th.

> @taramakage Is it okay to have UnknownTeam:@omercanyenigun and score 0? will it be fixed? I did all the tasks. If there is a mistake, I wrote it to be corrected. have a nice day

The reason for the 'UnknownTeam' error is that the evidence format is incorrect. In this case, you have inputted all your evidence starting from row 3 of each sheet, when in fact you should start from row 2. Please check the details in #376.

**Comment by rukideruki** [comment]
@taramakage Hi, I will make the necessary corrections, thank you. Will I be reconsidered for scoring?

**Comment by omercanyenigun** [comment]
@taramakage Hi, I will make the necessary corrections, thank you. Will I be reconsidered for scoring?

**Comment by omercanyenigun** [comment]
@taramakage I fixed the UnknownTeam bug. I uploaded the #541 e by updating the file. ( https://github.com/game-of-nfts/gon-evidence/pull/541 )

**Pull request merged**
