### PR TITLE
Add Evidence for Cypher Core

### PR DESCRIPTION
**Pull request by jim380**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Hey @jim380 , please use `jim380` as your directory name. Thx~

**Comment by jim380** [comment]
> Hey @jim380 , please use `jim380` as your directory name. Thx~

@taramakage done

**Review by taramakage — COMMENTED** [review]
Please remove the `jim380/.DS_Store` file.

**Comment by jim380** [comment]
> Please remove the `jim380/.DS_Store` file.

done

**Review by taramakage — APPROVED** [review]

**Pull request merged**
