### PR TITLE
Create evidence.xlsx genznodes team

### PR DESCRIPTION
**Pull request by PolkaVio**

### CODE REVIEW

**Comment by taramakage** [comment]
Hey @PolkaVio, why are you still making the pull request with the account name `PolkdaVio`? :laughing: I'm sorry if I confused you in your last pull request. If you use the username `PolkaVio`, your directory name should be `PolkaVio/evidence.xlsx`. If you use `genznodes-ecosystem`, then it should be `genznodes-ecosystem/evidence.xlsx`. We require this because we use your GitHub account name as the identifier in our verification program. Thank you for your understanding!

**Comment by PolkaVio** [comment]
@taramakage genznodes-ecosystem is organization https://github.com/genznodes-ecosystem/gon-evidence , that's why I asked first if I need to fork my account, your answer is enough on genznodes-ecosystem.
wth

**Comment by taramakage** [comment]
Well well, my bad. :sos: I didn't realize that's an Organization Account.

**Comment by PolkaVio** [comment]
no worries @taramakage ! , and then I close pr and create with my account ? or wat?

and can I change name directory with genznodes ?

**Comment by taramakage** [comment]
> no worries @taramakage ! , and then I close pr and create with my account ? or wat?
> 
> and can I change name directory with genznodes ?

Keep this PR. Just change the directory name to `PolkaVio` and then I will merge it.

**Review by taramakage — APPROVED** [review]

**Pull request merged**
