### PR TITLE
add evidence for Cosmostation

### PR DESCRIPTION
**Pull request by carameleon**

### CODE REVIEW

**Review by taramakage — APPROVED** [review]

**Comment by taramakage** [comment]
Hi @carameleon, just a reminder here that you have a typo of uptick addr in your info sheet.

```
got: uptick1vhgy442zrgtxh9s5pag7czscuqm82svznydlhf 4
wanted: uptick1vhgy442zrgtxh9s5pag7czscuqm82svznydlhf4
```

**Comment by taramakage** [comment]
The checksum is incorrect as well.

```
uptick1vhgy442zrgtxh9s5pag7czscuqm82svznydlhf4,err:invalid checksum (expected ydlhgp got ydlhf4)
```

**Comment by carameleon** [comment]
@taramakage 
sorry for bothering due to typo
the correct address is `uptick1vhgy442zrgtxh9s5pag7czscuqm82svznydlhf`
should I PR again?

**Comment by taramakage** [comment]
PR please!

> @taramakage sorry for bothering due to typo the correct address is `uptick1vhgy442zrgtxh9s5pag7czscuqm82svznydlhf` should I PR again?

Please PR!

**Pull request merged**
