### PR TITLE
evidence.xlsx

### PR DESCRIPTION
**Pull request by OlegBirkoff**
[evidence.xlsx](https://github.com/game-of-nfts/gon-evidence/files/10881136/evidence.xlsx)

### CODE REVIEW

**Comment by taramakage** [comment]
Seems you didn't put the evidence file under your folder?

**Comment by OlegBirkoff** [comment]
I put the file in the folder
image

**Comment by taramakage** [comment]
> I put the file in the folder image

Got it. In fact you should copy the evidence file from `./template` directory to your own and add your info. Don't just create an empty evidence file :smiley:

**Comment by OlegBirkoff** [comment]
Please check. I have corrected it.

**Comment by OlegBirkoff** [comment]
> > I put the file in the folder image
> 
> Got it. In fact you should copy the evidence file from `./template` directory to your own and add your info. Don't just create an empty evidence file 😃


Please check. I have corrected it.

**Comment by OlegBirkoff** [comment]
I have completed all assignments A1-A6 Stage-1. 
Please check and add me to https://github.com/game-of-nfts/gon-evidence 
I have previously completed the form and I have a GoNear role in discord.

**Review by taramakage — APPROVED** [review]

**Pull request merged**
