### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Daniiel-X**

### CODE REVIEW

**Comment by taramakage** [comment]
Closing this for github account register time is less than one year.

**Comment by Daniiel-X** [comment]
Why closing? I am joined in Github March 9 2022. One year ago :(

**Comment by taramakage** [comment]
Because the game started at March 1. Sorry for that...

**Comment by Daniiel-X** [comment]
> Because the game started at March 1. Sorry for that...

But I submitted the assignment after March 9 and it turns out my profile fits the conditions for participation. In my opinion it is illogical to exclude me because of the difference in a few days.

**Comment by taramakage** [comment]
> > Because the game started at March 1. Sorry for that...
> 
> But I submitted the assignment after March 9 and it turns out my profile fits the conditions for participation. In my opinion it is illogical to exclude me because of the difference in a few days.

Sounds reasonable. So I'll reopen and merge you.

**Review by taramakage — APPROVED** [review]

**Pull request merged**
