### PR TITLE
Omercanyenigun evidence

### PR DESCRIPTION
**Pull request by omercanyenigun**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Hey @omercanyenigun, it seems that we can't find your registration info in our forms. I will contact my colleague about this.

**Comment by omercanyenigun** [comment]
> 

first i created pr then i filled the form

**Comment by omercanyenigun** [comment]
> Hey @omercanyenigun, it seems that we can't find your registration info in our forms. I will contact my colleague about this.

@taramakage hi first i created pr then i filled the form

**Comment by taramakage** [comment]
> > Hey @omercanyenigun, it seems that we can't find your registration info in our forms. I will contact my colleague about this.
> 
> @taramakage hi first i created pr then i filled the form

@omercanyenigun Got it. Please wait and we'll check it.

**Comment by omercanyenigun** [comment]
> 



> > > Hey @omercanyenigun, it seems that we can't find your registration info in our forms. I will contact my colleague about this.
> > 
> > 
> > @taramakage hi first i created pr then i filled the form
> 
> @omercanyenigun Got it. Please wait and we'll check it.

thank you

**Comment by taramakage** [comment]
Forgot one thing! Can you move your directory to the root path? 

`./template/omercanyenigun/..` => `./omomercanyenigun/..`

**Comment by omercanyenigun** [comment]
> Forgot one thing! Can you move your directory to the root path?
> 
> `./template/omercanyenigun/..` => `./omomercanyenigun/..`

i carried  gon-evidence/omercanyenigun/evidence.xlsx

**Review by taramakage — APPROVED** [review]

**Pull request merged**
