### PR TITLE
Add Gavryushev evidence

### PR DESCRIPTION
**Pull request by olegufa6565**

### CODE REVIEW

**Review by taramakage — COMMENTED** [review]
Hey @olegufa6565, we notice the registration time of the GitHub account is less than one year. cry

**Comment by olegufa6565** [comment]
is this a condition for participation?this is really my account. I created it about 10 months ago.

**Comment by taramakage** [comment]
> is this a condition for participation?this is really my account. I created it about 10 months ago.

We set this threshold to filter out spam accounts, but we understand that it may affect some legitimate developers whose accounts don't meet this requirement. We suggest that you use an account that has been active for over a year to participate in the game. Thank you for your understanding.

**Comment by olegufa6565** [comment]
I don't have such an account. I started doing testnets in May last year.

**Pull request closed without merging**
