### PR TITLE
add evidence

### PR DESCRIPTION
**Pull request by rukideruki**

### CODE REVIEW

**Comment by taramakage** [comment]
Hey @rukideruki, we can't find you in our registration form. Have you registered before?

**Comment by rukideruki** [comment]
> Hey @rukideruki, we can't find you in our registration form. Have you registered before?

@taramakage hey, I filled the form after sending the file. it needs to reach you

**Comment by rukideruki** [comment]
@taramakage hey, I filled the form after sending the file. it needs to reach you

**Comment by taramakage** [comment]
Hey @rukideruki, we noticed that your GitHub account was registered less than a year ago. We set this threshold to filter out spam accounts, but we understand that it may affect some legitimate developers whose accounts don't meet this requirement. We suggest that you use an account that has been active for over a year to participate in the game. Thank you for your understanding.

**Pull request closed without merging**
